export enum Role {
  ADMIN = "ADMIN",
  HEAD_OF_SALES = "HEAD_OF_SALES",
  TELE_SALES = "TELE_SALES",
  SALES = "SALES"
}
export enum LeadStatus {
  NEW = "NEW",
  CONTACTED = "CONTACTED",
  NO_ANSWER = "NO_ANSWER",
  NEEDS_FOLLOWUP = "NEEDS_FOLLOWUP",
  INTERESTED = "INTERESTED",
  NOT_INTERESTED = "NOT_INTERESTED",
  HOT = "HOT",
  COLD = "COLD",
  MEETING_SCHEDULED = "MEETING_SCHEDULED",
  TRANSFERRED_TO_SALES = "TRANSFERRED_TO_SALES",
  CLOSED_WON = "CLOSED_WON",
  CLOSED_LOST = "CLOSED_LOST"
}
export enum LeadTier {
  LEAD = "LEAD",
  HOT = "HOT",
  COLD = "COLD"
}
export enum MeetingStatus {
  SCHEDULED = "SCHEDULED",
  DONE = "DONE",
  POSTPONED = "POSTPONED",
  CANCELLED = "CANCELLED"
}
export enum LeadSource {
  EXCEL_UPLOAD = "EXCEL_UPLOAD",
  MANUAL = "MANUAL"
}
export enum ActivityType {
  STATUS_CHANGE = "STATUS_CHANGE",
  FOLLOWUP_CREATED = "FOLLOWUP_CREATED",
  FOLLOWUP_COMPLETED = "FOLLOWUP_COMPLETED",
  MEETING_SCHEDULED = "MEETING_SCHEDULED",
  MEETING_UPDATED = "MEETING_UPDATED",
  TRANSFERRED = "TRANSFERRED",
  NOTE = "NOTE",
  LEAD_CREATED = "LEAD_CREATED",
  LEAD_ASSIGNED = "LEAD_ASSIGNED"
}
